language: dart
# Speed up builds by using containerization.
sudo: false
dart:
- stable
- dev
with_content_shell: false
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - set -e
  - pub run test test/rxdart_test.dart
  - pub run --mode=release test/benchmarks/plain_benchmark.dart
  - pub run --mode=release test/benchmarks/map_benchmark.dart
  - pub run --mode=release test/benchmarks/merge_benchmark.dart
  - pub run --mode=release test/benchmarks/combine_latest_benchmark.dart
  - pub run --mode=release test/benchmarks/zip_benchmark.dart
  - pub run --mode=release test/benchmarks/debounce_benchmark.dart
  - pub run --mode=release test/benchmarks/start_with_benchmark.dart
  - pub run --mode=release test/benchmarks/flat_map_benchmark.dart
  - pub run --mode=release test/benchmarks/flat_map_latest_benchmark.dart
after_success:
  - pub global activate dart_coveralls
  - pub global run dart_coveralls:dart_coveralls report --debug --exclude-test-files --token=$REPO_TOKEN test/rxdart_test.dart