language: dart
sudo: false
dart:
  - dev
  - stable
with_content_shell: false
script:
  - pub global activate coverage
  - dartfmt -n ./lib --set-exit-if-changed
  - dartanalyzer --fatal-infos --fatal-warnings ./
  - pub run test test/rxdart_test.dart --coverage=coverage
  - pub global run coverage:format_coverage --in coverage/test/rxdart_test.dart.vm.json --out lcov.info --lcov
after_success:
  - bash <(curl -s https://codecov.io/bash)
