name: rxdart
version: 0.1.0+6
author: Frank Pepermans <frank@igindo.com>
description: A wrapper for the RxJs library
homepage: https://github.com/frankpepermans/rxdart
environment:
  sdk: '>1.12.0'
dependencies:
  browser: ^0.10.0+2
  js: ^0.6.0-beta
  test: ^0.12.5+1
