name: rxdart
version: 0.2.0+2
author: Frank Pepermans <frank@igindo.com>
description: A wrapper for the RxJs library
homepage: https://github.com/frankpepermans/rxdart
environment:
  sdk: '>1.12.0'
dependencies:
  browser: ^0.10.0+2
  faker: any
  js: ^0.6.0-beta
  react: any
  test: ^0.12.5+1
