name: rxdart
version: 0.3.0
author: Frank Pepermans <frank@igindo.com>
description: Native Dart rx implementation
homepage: https://github.com/frankpepermans/rxdart
environment:
  sdk: '>1.12.0'
dependencies:
  browser: ^0.10.0+2
dev_dependencies:
  faker: ^0.0.4
  react: ^0.8.2
  test: ^0.12.5+1
