name: rxdart_examples
version: 0.15.1
authors:
- Frank Pepermans <frank@igindo.com>
- Brian Egan <brian@brianegan.com>
description: Some examples which use Rx
homepage: https://github.com/ReactiveX/rxdart
environment:
  sdk: '>=1.21.0 <2.0.0'
dependencies:
  rxdart:
    path: ../../../rxdart
  http: ^0.11.3
web:
  compiler:
    debug: dartdevc
